# The URL the site will be built for
base_url = "https://m.ichael.dk"
generate_rss = true
compile_sass = false

title = "MD Kuc"
description = "Software Engineer"
highlight_code = true

# For other themes see:
# https://www.getzola.org/documentation/getting-started/configuration#syntax-highlighting
highlight_theme = "dimmed-fluid"

taxonomies = [
	{ name = "categories", paginate_by = 3, rss = true },
	{ name = "tags", paginate_by = 3 }
]

[extra]
author = "Michael Kuc"
menus = [ "about.md", "skills.md" ]
customJS = []
logoTitle = "Michael Daniel Kuc"

postSummaryDateFormat = "%Y-%m"
postPageDateFormat = "%Y-%m-%d %H:%M"

#twitter = "Your Twitter username"
#facebook = "Your Facebook username"
